### ISSUE TITLE
Changing the background programmatically!

### ISSUE THREAD

**Issue by khaledkhj** [hidrodixtion/Android-Diagonal-Cut-View#1]
Thanks for this great tip to create such a nice image,
but is there any way to change the background programmatically?
for example, to load the user image profile and show it instead of just showing fixed image!

Thanks in advance,

**Comment by hidrodixtion** [comment]
Yes, there is. If you want to retrieve image from server you can try [Glide](https://github.com/bumptech/glide) or [Picasso](https://github.com/square/picasso).
